### ISSUE TITLE
Multiple keyword pattern

### ISSUE THREAD

**Issue by hawk-king** [gavynriebau/delete-lines#2]
Hi, 

Could you add possibility to create multiple keyword pattern, like: POST;GET.?
Maybe it exist already?

Thanks,
HK

**Comment by gavynriebau** [comment]
Hi hawk-king,

You can do this by entering "(POST|GET)", e.g.

![filter_to_post_or_get](https://cloud.githubusercontent.com/assets/11895736/9075233/15603b38-3b45-11e5-8339-c50df3dffac6.gif)

**Comment by hawk-king** [comment]
Great, Thanks!
