### ISSUE TITLE
Delete empty new lines?

### ISSUE THREAD

**Issue by orschiro** [gavynriebau/delete-lines#6]
Hey @gavynriebau 

Thanks for your promising package!

Was hoping to delete empty lines with it. 

Is this possible with a pattern?

Thanks!

![image](https://user-images.githubusercontent.com/170947/38270197-f4c9cd0c-3782-11e8-8fb6-9113056a9710.png)

**Comment by gavynriebau** [comment]
If you enable regexes by pressing the `.*` button the following expression should then delete empty lines:
`^\s*$`

The expression can be broken down as meaning:
* `^` start of line
* `\s*` zero or more spaces
* `$` end of line

**Comment by orschiro** [comment]
@gavynriebau 

> If you enable regexes by pressing the .* button the following expression should then delete empty lines:
^\s*$

This is working great, thanks!
